/*
 * Copyright © 2014 <code@io7m.com> http://io7m.com
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package com.io7m.jparasol.xml;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Collections;
import java.util.Map.Entry;
import java.util.SortedMap;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import javax.xml.transform.Source;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.SchemaFactory;

import nu.xom.Attribute;
import nu.xom.Builder;
import nu.xom.Document;
import nu.xom.Element;
import nu.xom.Elements;
import nu.xom.ParsingException;
import nu.xom.ValidityException;

import org.xml.sax.ErrorHandler;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;
import org.xml.sax.XMLReader;

import com.io7m.jequality.annotations.EqualityReference;
import com.io7m.jlog.LogUsableType;
import com.io7m.jnull.NullCheck;
import com.io7m.jnull.Nullable;
import com.io7m.junreachable.UnreachableCodeException;

/**
 * Metadata about a GLSL program generated by Parasol.
 */

@EqualityReference public final class PGLSLMetaXML
{
  @EqualityReference private static class TrivialErrorHandler implements
    ErrorHandler
  {
    private @Nullable SAXParseException exception;

    public TrivialErrorHandler()
    {

    }

    @Override public void error(
      final @Nullable SAXParseException e)
      throws SAXException
    {
      this.exception = e;
    }

    @Override public void fatalError(
      final @Nullable SAXParseException e)
      throws SAXException
    {
      this.exception = e;
    }

    public @Nullable SAXParseException getException()
    {
      return this.exception;
    }

    @Override public void warning(
      final @Nullable SAXParseException e)
      throws SAXException
    {
      this.exception = e;
    }
  }

  /**
   * The XML URI string.
   */

  public static final String XML_URI_STRING;

  /**
   * The schema XML URI.
   */

  public static final URI    XML_URI;

  /**
   * The schema version.
   */

  public static final int    XML_VERSION;

  static {
    try {
      XML_URI_STRING = "http://schemas.io7m.com/parasol/glsl-meta";
      XML_URI = new URI(PGLSLMetaXML.XML_URI_STRING);
      XML_VERSION = 3;
    } catch (final URISyntaxException e) {
      throw new UnreachableCodeException(e);
    }
  }

  /**
   * Extract metadata from the given document.
   * 
   * @throws ValidityException
   *           Iff the given document is not a valid metadata document.
   */

  private static PGLSLMetaXML fromDocument(
    final Document doc)
    throws ValidityException
  {
    NullCheck.notNull(doc, "Document");

    final Element root = doc.getRootElement();

    if ("meta".equals(root.getLocalName()) == false) {
      final StringBuilder message = new StringBuilder();
      message.append("Expected an element 'meta', but got '");
      message.append(root.getLocalName());
      message.append("'");
      throw new ValidityException(message.toString());
    }

    final Attribute version =
      root.getAttribute("version", PGLSLMetaXML.XML_URI_STRING);
    assert version != null;

    try {
      final int version_number = Integer.parseInt(version.getValue());
      if (version_number != PGLSLMetaXML.XML_VERSION) {
        final StringBuilder message = new StringBuilder();
        message.append("Unsupported version ");
        message.append(version_number);
        message.append(", supported versions are: ");
        message.append(PGLSLMetaXML.XML_VERSION);
        throw new ValidityException(message.toString());
      }
    } catch (final NumberFormatException x) {
      final StringBuilder message = new StringBuilder();
      message
        .append("Could not parse 'version' attribute as numeric value: ");
      message.append(x.getMessage());
      throw new ValidityException(message.toString());
    }

    final String rname = PGLSLMetaXML.parseName(root);
    final SortedSet<Integer> rsupports_es =
      PGLSLMetaXML.parseSupportsES(root);
    final SortedSet<Integer> rsupports_full =
      PGLSLMetaXML.parseSupportsFull(root);

    final SortedSet<FragmentInput> fragment_inputs =
      PGLSLMetaXML.parseFragmentInputs(root);
    final SortedSet<FragmentParameter> fragment_parameters =
      PGLSLMetaXML.parseFragmentParameters(root);
    final SortedMap<Integer, FragmentOutput> fragment_outputs =
      PGLSLMetaXML.parseFragmentOutputs(root);

    final SortedSet<VertexInput> vertex_inputs =
      PGLSLMetaXML.parseVertexInputs(root);
    final SortedSet<VertexParameter> vertex_parameters =
      PGLSLMetaXML.parseVertexParameters(root);
    final SortedSet<VertexOutput> vertex_outputs =
      PGLSLMetaXML.parseVertexOutputs(root);

    final SortedMap<Version, CompactedShaders> compact_mappings =
      PGLSLMetaXML.parseCompactions(root);

    return new PGLSLMetaXML(
      rname,
      rsupports_es,
      rsupports_full,
      vertex_inputs,
      vertex_parameters,
      vertex_outputs,
      fragment_inputs,
      fragment_parameters,
      fragment_outputs,
      compact_mappings);
  }

  /**
   * Load XML metadata from the given stream.
   * 
   * @param stream
   *          The stream
   * @param log
   *          A log interface
   * @return XML metadata
   * @throws ParsingException
   *           On parse errors
   * @throws IOException
   *           On I/O errors
   * @throws SAXException
   *           On parse errors
   * @throws ParserConfigurationException
   *           On parser configuration errors
   */

  public static PGLSLMetaXML fromStream(
    final InputStream stream,
    final LogUsableType log)
    throws ParsingException,
      IOException,
      SAXException,
      ParserConfigurationException
  {
    return PGLSLMetaXML.fromDocument(PGLSLMetaXML.fromStreamValidate(
      stream,
      log));
  }

  static Document fromStreamValidate(
    final InputStream stream,
    final LogUsableType log)
    throws SAXException,
      ParserConfigurationException,
      ValidityException,
      ParsingException,
      IOException
  {
    NullCheck.notNull(stream, "Stream");
    NullCheck.notNull(log, "Log");

    final LogUsableType log_xml = log.with("xml");

    log_xml.debug("creating sax parser");
    final SAXParserFactory factory = SAXParserFactory.newInstance();
    factory.setValidating(false);
    factory.setNamespaceAware(true);

    log_xml.debug("opening schema");
    final InputStream xsd_stream =
      PGLSLMetaXML.class.getResourceAsStream("/com/io7m/jparasol/meta.xsd");

    try {
      log_xml.debug("creating schema handler");
      final SchemaFactory sf =
        SchemaFactory.newInstance("http://www.w3.org/2001/XMLSchema");

      final Source[] sources = new Source[1];
      sources[0] = new StreamSource(xsd_stream);
      factory.setSchema(sf.newSchema(sources));

      final TrivialErrorHandler handler = new TrivialErrorHandler();
      final SAXParser parser = factory.newSAXParser();
      final XMLReader reader = parser.getXMLReader();
      reader.setErrorHandler(handler);

      log_xml.debug("parsing and validating");
      final Builder builder = new Builder(reader);
      final Document doc = builder.build(stream);

      final SAXParseException ex = handler.getException();
      if (ex != null) {
        throw ex;
      }

      return doc;
    } finally {
      xsd_stream.close();
    }
  }

  private static @Nullable
    SortedMap<Version, CompactedShaders>
    parseCompactions(
      final Element root)
      throws ValidityException
  {
    final SortedMap<Version, CompactedShaders> m =
      new TreeMap<Version, CompactedShaders>();

    final Elements ecm =
      root.getChildElements("compact-mappings", PGLSLMetaXML.XML_URI_STRING);
    if (ecm.size() == 0) {
      return null;
    }

    final Elements ecms =
      ecm.get(0).getChildElements("mapping", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < ecms.size(); ++index) {
      final Element em = ecms.get(index);

      final Attribute av =
        em.getAttribute("number", PGLSLMetaXML.XML_URI_STRING);
      final Attribute afh =
        em.getAttribute("fragment-hash", PGLSLMetaXML.XML_URI_STRING);
      final Attribute avh =
        em.getAttribute("vertex-hash", PGLSLMetaXML.XML_URI_STRING);
      final Attribute aa =
        em.getAttribute("api", PGLSLMetaXML.XML_URI_STRING);

      try {
        final String sv = avh.getValue();
        final String sf = afh.getValue();
        assert sv != null;
        assert sf != null;

        final CompactedShaders cs = new CompactedShaders(sv, sf);
        final String v_api = aa.getValue();
        assert v_api != null;
        final API api = API.fromString(v_api);
        final Version v = new Version(Integer.parseInt(av.getValue()), api);
        m.put(v, cs);
      } catch (final NumberFormatException x) {
        throw new ValidityException(
          "Could not parse 'version' number on 'mapping' element: "
            + x.getMessage());
      }
    }

    return m;
  }

  private static SortedSet<FragmentInput> parseFragmentInputs(
    final Element root)
  {
    final SortedSet<FragmentInput> rinputs = new TreeSet<FragmentInput>();

    final Elements eins =
      root.getChildElements(
        "declared-fragment-inputs",
        PGLSLMetaXML.XML_URI_STRING);

    final Element ei = eins.get(0);
    final Elements eic =
      ei.getChildElements("input", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eic.size(); ++index) {
      final Element e = eic.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);

      final FragmentInput o = new FragmentInput(an.getValue(), at.getValue());
      rinputs.add(o);
    }

    return rinputs;
  }

  private static SortedMap<Integer, FragmentOutput> parseFragmentOutputs(
    final Element root)
    throws ValidityException
  {
    final SortedMap<Integer, FragmentOutput> routputs =
      new TreeMap<Integer, FragmentOutput>();

    final Elements es =
      root.getChildElements(
        "declared-fragment-outputs",
        PGLSLMetaXML.XML_URI_STRING);
    final Element eo = es.get(0);
    final Elements eoc =
      eo.getChildElements("fragment-output", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eoc.size(); ++index) {
      final Element e = eoc.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);
      final Attribute ai =
        e.getAttribute("index", PGLSLMetaXML.XML_URI_STRING);

      try {
        @SuppressWarnings({ "boxing" }) final FragmentOutput o =
          new FragmentOutput(
            Integer.parseInt(ai.getValue()),
            an.getValue(),
            at.getValue());
        routputs.put(o.getIndex(), o);
      } catch (final NumberFormatException x) {
        throw new ValidityException(
          "Could not parse 'index' number on 'fragment-output' element: "
            + x.getMessage());
      }
    }

    return routputs;
  }

  private static SortedSet<FragmentParameter> parseFragmentParameters(
    final Element root)
  {
    final SortedSet<FragmentParameter> rinputs =
      new TreeSet<FragmentParameter>();

    final Elements eins =
      root.getChildElements(
        "declared-fragment-parameters",
        PGLSLMetaXML.XML_URI_STRING);

    final Element ei = eins.get(0);
    final Elements eic =
      ei.getChildElements("parameter", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eic.size(); ++index) {
      final Element e = eic.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);

      final FragmentParameter o =
        new FragmentParameter(an.getValue(), at.getValue());
      rinputs.add(o);
    }

    return rinputs;
  }

  private static String parseName(
    final Element root)
  {
    final Elements ename =
      root.getChildElements("program-name", PGLSLMetaXML.XML_URI_STRING);
    return ename.get(0).getValue();
  }

  private static SortedSet<Integer> parseSupportsES(
    final Element root)
    throws ValidityException
  {
    final SortedSet<Integer> versions = new TreeSet<Integer>();

    final Elements supports =
      root.getChildElements("supports", PGLSLMetaXML.XML_URI_STRING);

    final Element es = supports.get(0);
    final Elements esc =
      es.getChildElements("version", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < esc.size(); ++index) {
      final Element e = esc.get(index);
      final Attribute av =
        e.getAttribute("number", PGLSLMetaXML.XML_URI_STRING);
      final Attribute aa = e.getAttribute("api", PGLSLMetaXML.XML_URI_STRING);

      try {
        final int avi = Integer.parseInt(av.getValue());

        final String aas = aa.getValue();
        if ("glsl-es".equals(aas)) {
          versions.add(Integer.valueOf(avi));
        }

      } catch (final NumberFormatException x) {
        throw new ValidityException(
          "Could not parse number attribute on version element");
      }
    }

    return versions;
  }

  private static SortedSet<Integer> parseSupportsFull(
    final Element root)
    throws ValidityException
  {
    final SortedSet<Integer> versions = new TreeSet<Integer>();

    final Elements supports =
      root.getChildElements("supports", PGLSLMetaXML.XML_URI_STRING);

    final Element es = supports.get(0);
    final Elements esc =
      es.getChildElements("version", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < esc.size(); ++index) {
      final Element e = esc.get(index);
      final Attribute av =
        e.getAttribute("number", PGLSLMetaXML.XML_URI_STRING);
      final Attribute aa = e.getAttribute("api", PGLSLMetaXML.XML_URI_STRING);

      try {
        final int avi = Integer.parseInt(av.getValue());

        final String aas = aa.getValue();
        if ("glsl".equals(aas)) {
          versions.add(Integer.valueOf(avi));
        }

      } catch (final NumberFormatException x) {
        throw new ValidityException(
          "Could not parse number attribute on version element");
      }
    }

    return versions;
  }

  private static SortedSet<VertexInput> parseVertexInputs(
    final Element root)
  {
    final SortedSet<VertexInput> rinputs = new TreeSet<VertexInput>();

    final Elements eins =
      root.getChildElements(
        "declared-vertex-inputs",
        PGLSLMetaXML.XML_URI_STRING);
    final Element ei = eins.get(0);
    final Elements eic =
      ei.getChildElements("input", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eic.size(); ++index) {
      final Element e = eic.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);
      final VertexInput o = new VertexInput(an.getValue(), at.getValue());
      rinputs.add(o);
    }

    return rinputs;
  }

  private static SortedSet<VertexOutput> parseVertexOutputs(
    final Element root)
  {
    final SortedSet<VertexOutput> routputs = new TreeSet<VertexOutput>();

    final Elements es =
      root.getChildElements(
        "declared-vertex-outputs",
        PGLSLMetaXML.XML_URI_STRING);

    final Element eo = es.get(0);
    final Elements eoc =
      eo.getChildElements("output", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eoc.size(); ++index) {
      final Element e = eoc.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);
      final VertexOutput o = new VertexOutput(an.getValue(), at.getValue());
      routputs.add(o);
    }

    return routputs;
  }

  private static SortedSet<VertexParameter> parseVertexParameters(
    final Element root)
  {
    final SortedSet<VertexParameter> rinputs = new TreeSet<VertexParameter>();

    final Elements eins =
      root.getChildElements(
        "declared-vertex-parameters",
        PGLSLMetaXML.XML_URI_STRING);

    final Element ei = eins.get(0);
    final Elements eic =
      ei.getChildElements("parameter", PGLSLMetaXML.XML_URI_STRING);

    for (int index = 0; index < eic.size(); ++index) {
      final Element e = eic.get(index);
      final Attribute an =
        e.getAttribute("name", PGLSLMetaXML.XML_URI_STRING);
      final Attribute at =
        e.getAttribute("type", PGLSLMetaXML.XML_URI_STRING);
      final VertexParameter o =
        new VertexParameter(an.getValue(), at.getValue());
      rinputs.add(o);
    }

    return rinputs;
  }

  private static Element toXMLCompactMapping(
    final Version v,
    final CompactedShaders cs)
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:mapping", uri);
    e.addAttribute(new Attribute("g:number", uri, Integer.toString(v
      .getVersion())));
    e.addAttribute(new Attribute("g:api", uri, v.getAPI().getName()));
    e.addAttribute(new Attribute("g:fragment-hash", uri, cs
      .getFragmentShader()));
    e.addAttribute(new Attribute("g:vertex-hash", uri, cs.getVertexShader()));
    return e;
  }

  private static Element toXMLVersionES(
    final Integer v)
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:version", uri);
    e.addAttribute(new Attribute("g:number", uri, v.toString()));
    e.addAttribute(new Attribute("g:api", uri, "glsl-es"));
    return e;
  }

  private static Element toXMLVersionFull(
    final Integer v)
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:version", uri);
    e.addAttribute(new Attribute("g:number", uri, v.toString()));
    e.addAttribute(new Attribute("g:api", uri, "glsl"));
    return e;
  }

  private final @Nullable SortedMap<Version, CompactedShaders> compact_mappings;
  private final SortedSet<FragmentInput>                       fragment_inputs;
  private final SortedMap<Integer, FragmentOutput>             fragment_outputs;
  private final SortedSet<FragmentParameter>                   fragment_parameters;
  private final String                                         name;
  private final SortedSet<Integer>                             supports_es;
  private final SortedSet<Integer>                             supports_full;
  private final SortedSet<VertexInput>                         vertex_inputs;
  private final SortedSet<VertexOutput>                        vertex_outputs;
  private final SortedSet<VertexParameter>                     vertex_parameters;

  private PGLSLMetaXML(
    final String in_name,
    final SortedSet<Integer> in_supports_es,
    final SortedSet<Integer> in_supports_full,
    final SortedSet<VertexInput> in_vertex_inputs,
    final SortedSet<VertexParameter> in_vertex_parameters,
    final SortedSet<VertexOutput> in_vertex_outputs,
    final SortedSet<FragmentInput> in_fragment_inputs,
    final SortedSet<FragmentParameter> in_fragment_parameters,
    final SortedMap<Integer, FragmentOutput> in_fragment_outputs,
    final @Nullable SortedMap<Version, CompactedShaders> in_compact_mappings)
  {
    this.name = NullCheck.notNull(in_name, "Name");
    this.supports_es = NullCheck.notNull(in_supports_es, "ES versions");
    this.supports_full = NullCheck.notNull(in_supports_full, "Full versions");

    this.vertex_parameters =
      NullCheck.notNull(in_vertex_parameters, "Vertex parameters");
    this.vertex_inputs = NullCheck.notNull(in_vertex_inputs, "Vertex inputs");
    this.vertex_outputs =
      NullCheck.notNull(in_vertex_outputs, "Vertex outputs");

    this.fragment_parameters =
      NullCheck.notNull(in_fragment_parameters, "Fragment parameters");
    this.fragment_inputs =
      NullCheck.notNull(in_fragment_inputs, "Fragment inputs");
    this.fragment_outputs =
      NullCheck.notNull(in_fragment_outputs, "Fragment outputs");

    this.compact_mappings = in_compact_mappings;
  }

  /**
   * @return The mappings from version numbers to file hashes, iff the shaders
   *         for this program are stored in compacted form.
   * 
   * @throws IllegalArgumentException
   *           Iff {@link #isCompacted()} <code>== false</code>.
   */

  public SortedMap<Version, CompactedShaders> getCompactMappings()
    throws IllegalArgumentException
  {
    if (this.isCompacted() == false) {
      throw new IllegalArgumentException("Program is not compacted");
    }

    final SortedMap<Version, CompactedShaders> r =
      Collections.unmodifiableSortedMap(this.compact_mappings);
    assert r != null;
    return r;
  }

  /**
   * @return The set of fragment shader inputs that were declared in the given
   *         program.
   */

  public SortedSet<FragmentInput> getDeclaredFragmentInputs()
  {
    return this.fragment_inputs;
  }

  /**
   * @return All of the declared fragment shader outputs.
   */

  public SortedMap<Integer, FragmentOutput> getDeclaredFragmentOutputs()
  {
    final SortedMap<Integer, FragmentOutput> r =
      Collections.unmodifiableSortedMap(this.fragment_outputs);
    assert r != null;
    return r;
  }

  /**
   * @return The set of fragment shader parameters that were declared in the
   *         given program.
   */

  public SortedSet<FragmentParameter> getDeclaredFragmentParameters()
  {
    return this.fragment_parameters;
  }

  /**
   * @return The set of vertex shader inputs that were declared in the given
   *         program.
   */

  public SortedSet<VertexInput> getDeclaredVertexInputs()
  {
    return this.vertex_inputs;
  }

  /**
   * @return The set of vertex shader outputs that were declared in the given
   *         program.
   */

  public SortedSet<VertexOutput> getDeclaredVertexOutputs()
  {
    return this.vertex_outputs;
  }

  /**
   * @return The set of vertex shader parameters that were declared in the
   *         given program.
   */

  public SortedSet<VertexParameter> getDeclaredVertexParameters()
  {
    return this.vertex_parameters;
  }

  /**
   * @return The fully-qualified name of the program as it was declared in the
   *         original Parasol source.
   */

  public String getName()
  {
    return this.name;
  }

  /**
   * @return All of the versions of GLSL ES on which this program is
   *         supported.
   */

  public SortedSet<Integer> getSupportsES()
  {
    final SortedSet<Integer> r =
      Collections.unmodifiableSortedSet(this.supports_es);
    assert r != null;
    return r;
  }

  /**
   * @return All of the versions of GLSL on which this program is supported.
   */

  public SortedSet<Integer> getSupportsFull()
  {
    final SortedSet<Integer> r =
      Collections.unmodifiableSortedSet(this.supports_full);
    assert r != null;
    return r;
  }

  /**
   * @return <code>true</code> if the shaders for this program are stored in
   *         compacted form.
   */

  public boolean isCompacted()
  {
    return this.compact_mappings != null;
  }

  /**
   * Serialize metadata to XML.
   * 
   * @return An XML element
   */

  public Element toXML()
  {
    final Element root = new Element("g:meta", PGLSLMetaXML.XML_URI_STRING);
    root.addAttribute(new Attribute(
      "g:version",
      PGLSLMetaXML.XML_URI_STRING,
      Integer.toString(PGLSLMetaXML.XML_VERSION)));
    root.appendChild(this.toXMLProgramName());
    root.appendChild(this.toXMLSupports());
    root.appendChild(this.toXMLDeclaredVertexParameters());
    root.appendChild(this.toXMLDeclaredFragmentParameters());
    root.appendChild(this.toXMLDeclaredVertexInputs());
    root.appendChild(this.toXMLDeclaredFragmentInputs());
    root.appendChild(this.toXMLDeclaredVertexOutputs());
    root.appendChild(this.toXMLDeclaredFragmentOutputs());

    if (this.isCompacted()) {
      root.appendChild(this.toXMLCompactMappings());
    }
    return root;
  }

  private Element toXMLCompactMappings()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:compact-mappings", uri);

    final SortedMap<Version, CompactedShaders> map = this.compact_mappings;
    assert map != null;

    for (final Entry<Version, CompactedShaders> k : map.entrySet()) {
      final Version v = k.getKey();
      final CompactedShaders cs = k.getValue();
      switch (v.getAPI()) {
        case API_GLSL:
        {
          e.appendChild(PGLSLMetaXML.toXMLCompactMapping(v, cs));
          break;
        }
        case API_GLSL_ES:
        {
          e.appendChild(PGLSLMetaXML.toXMLCompactMapping(v, cs));
          break;
        }
      }
    }

    return e;
  }

  private Element toXMLDeclaredFragmentInputs()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-fragment-inputs", uri);
    for (final FragmentInput f : this.getDeclaredFragmentInputs()) {
      e.appendChild(f.toXML());
    }
    return e;
  }

  private Element toXMLDeclaredFragmentOutputs()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-fragment-outputs", uri);
    for (final FragmentOutput f : this.getDeclaredFragmentOutputs().values()) {
      e.appendChild(f.toXML());
    }
    return e;
  }

  private Element toXMLDeclaredFragmentParameters()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-fragment-parameters", uri);
    for (final FragmentParameter f : this.getDeclaredFragmentParameters()) {
      e.appendChild(f.toXML());
    }
    return e;
  }

  private Element toXMLDeclaredVertexInputs()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-vertex-inputs", uri);
    for (final VertexInput v : this.getDeclaredVertexInputs()) {
      e.appendChild(v.toXML());
    }
    return e;
  }

  private Element toXMLDeclaredVertexOutputs()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-vertex-outputs", uri);
    for (final VertexOutput v : this.getDeclaredVertexOutputs()) {
      e.appendChild(v.toXML());
    }
    return e;
  }

  private Element toXMLDeclaredVertexParameters()
  {
    final String uri = PGLSLMetaXML.XML_URI_STRING;
    final Element e = new Element("g:declared-vertex-parameters", uri);
    for (final VertexParameter v : this.getDeclaredVertexParameters()) {
      e.appendChild(v.toXML());
    }
    return e;
  }

  private Element toXMLProgramName()
  {
    final Element e =
      new Element("g:program-name", PGLSLMetaXML.XML_URI_STRING);
    e.appendChild(this.name);
    return e;
  }

  private Element toXMLSupports()
  {
    final Element e = new Element("g:supports", PGLSLMetaXML.XML_URI_STRING);
    for (final Integer s : this.getSupportsES()) {
      e.appendChild(PGLSLMetaXML.toXMLVersionES(s));
    }
    for (final Integer s : this.getSupportsFull()) {
      e.appendChild(PGLSLMetaXML.toXMLVersionFull(s));
    }
    return e;
  }

  /**
   * @return This metadata with the added compaction mappings
   *         <code>mappings</code>.
   */

  public PGLSLMetaXML withCompaction(
    final SortedMap<Version, CompactedShaders> mappings)
  {
    if (this.isCompacted()) {
      throw new IllegalArgumentException("Program is already compacted");
    }

    return new PGLSLMetaXML(
      this.name,
      this.supports_es,
      this.supports_full,
      this.vertex_inputs,
      this.vertex_parameters,
      this.vertex_outputs,
      this.fragment_inputs,
      this.fragment_parameters,
      this.fragment_outputs,
      mappings);
  }
}
