/*
 * Copyright © 2014 <code@io7m.com> http://io7m.com
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package com.io7m.jparasol.glsl;

import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.io7m.jequality.annotations.EqualityReference;
import com.io7m.jfunctional.FunctionType;
import com.io7m.jfunctional.Some;
import com.io7m.jlog.LogLevel;
import com.io7m.jlog.LogUsableType;
import com.io7m.jnull.NullCheck;
import com.io7m.jnull.Nullable;
import com.io7m.jparasol.core.GVersionES;
import com.io7m.jparasol.core.GVersionFull;
import com.io7m.jparasol.core.GVersionType;
import com.io7m.jparasol.core.GVersionVisitorType;
import com.io7m.jparasol.glsl.ast.GASTExpressionType;
import com.io7m.jparasol.lexer.Position;
import com.io7m.jparasol.lexer.TokenIdentifierLower;
import com.io7m.jparasol.typed.ast.TASTDeclaration;
import com.io7m.jparasol.typed.ast.TASTDeclaration.TASTDExternal;
import com.io7m.jparasol.typed.ast.TASTDeclaration.TASTDFunctionDefined;
import com.io7m.jparasol.typed.ast.TASTDeclaration.TASTDFunctionExternal;
import com.io7m.jparasol.typed.ast.TASTDeclaration.TASTDValueDefined;
import com.io7m.jparasol.typed.ast.TASTDeclaration.TASTDValueExternal;
import com.io7m.jparasol.typed.ast.TASTEVariable;
import com.io7m.jparasol.typed.ast.TASTExpressionType;
import com.io7m.jparasol.typed.ast.TASTTermName;
import com.io7m.junreachable.UnreachableCodeException;

/**
 * An FFI.
 */

@EqualityReference public final class GFFI
{
  @EqualityReference private static final class GLSL_ES_orLessThanGLSL120 implements
    FunctionType<GVersionType, Boolean>
  {
    public GLSL_ES_orLessThanGLSL120()
    {
      // Nothing
    }

    @Override public Boolean call(
      final GVersionType x)
    {
      return x
        .versionAccept(new GVersionVisitorType<Boolean, UnreachableCodeException>() {
          @Override public Boolean versionVisitES(
            final GVersionES v)

          {
            return Boolean.TRUE;
          }

          @Override public Boolean versionVisitFull(
            final GVersionFull v)

          {
            if (v.compareTo(GVersionFull.GLSL_120) <= 0) {
              return Boolean.TRUE;
            }
            return Boolean.FALSE;
          }
        });
    }
  }

  private static final Map<String, FunctionType<GVersionType, Boolean>>              DECLARATION_FUNCTION_REQUIRED;
  private static final Map<String, FunctionType<TASTDValueExternal, TASTExpressionType>> DECLARATION_VALUE_EXPRESSIONS;
  private static final Map<String, GFFIExpressionEmitterType>                        EXPRESSION_EMITTERS;
  private static final FunctionType<GVersionType, Boolean>                           GLSL_ES_OR_LT_GLSL120;

  // CHECKSTYLE:OFF
  static {
    GLSL_ES_OR_LT_GLSL120 = new GLSL_ES_orLessThanGLSL120();

    DECLARATION_FUNCTION_REQUIRED =
      new HashMap<String, FunctionType<GVersionType, Boolean>>();
    GFFI.DECLARATION_FUNCTION_REQUIRED.put(
      "com_io7m_parasol_float_is_nan",
      GFFI.GLSL_ES_OR_LT_GLSL120);
    GFFI.DECLARATION_FUNCTION_REQUIRED.put(
      "com_io7m_parasol_float_is_infinite",
      GFFI.GLSL_ES_OR_LT_GLSL120);
    GFFI.DECLARATION_FUNCTION_REQUIRED.put(
      "com_io7m_parasol_float_sign",
      GFFI.GLSL_ES_OR_LT_GLSL120);
    GFFI.DECLARATION_FUNCTION_REQUIRED.put(
      "com_io7m_parasol_float_truncate",
      GFFI.GLSL_ES_OR_LT_GLSL120);

    DECLARATION_VALUE_EXPRESSIONS =
      new HashMap<String, FunctionType<TASTDValueExternal, TASTExpressionType>>();
    GFFI.DECLARATION_VALUE_EXPRESSIONS.put(
      "com_io7m_parasol_fragment_coordinate",
      new FunctionType<TASTDeclaration.TASTDValueExternal, TASTExpressionType>() {
        @Override public TASTExpressionType call(
          final TASTDValueExternal x)
        {
          final File file = new File("<generated>");
          final TokenIdentifierLower original =
            new TokenIdentifierLower(file, Position.ZERO, "gl_FragCoord");
          final TASTTermName name =
            new TASTTermName.TASTTermNameExternal(original, "gl_FragCoord");
          return new TASTEVariable(x.getType(), name);
        }
      });

    EXPRESSION_EMITTERS = new HashMap<String, GFFIExpressionEmitterType>();

    /**
     * Automatically generated by ffi-values.sh, do not edit.
     */

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_absolute",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_absolute(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_arc_cosine",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_arc_cosine(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_arc_sine",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_arc_sine(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_arc_tangent",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_arc_tangent(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_ceiling",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_ceiling(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_clamp",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_clamp(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_cosine",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_cosine(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_divide(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_equals",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_equals(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_floor",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_floor(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_greater",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_greater(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_greater_or_equal",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_float_greater_or_equal(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_interpolate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_is_infinite",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_is_infinite(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_is_nan",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_is_nan(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_lesser",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_lesser(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_lesser_or_equal",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_float_lesser_or_equal(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_maximum",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_maximum(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_minimum",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_minimum(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_modulo",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_modulo(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_power",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_power(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_round",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_round(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_sign",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_sign(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_sine",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_sine(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_square_root",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_square_root(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_tangent",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_tangent(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_float_truncate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_float_truncate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_integer_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_integer_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_integer_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_integer_divide(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_integer_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_integer_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_integer_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_integer_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_matrix3x3f_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_matrix3x3f_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_matrix3x3f_multiply_vector",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_matrix3x3f_multiply_vector(
              f,
              arguments,
              version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_matrix4x4f_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_matrix4x4f_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_matrix4x4f_multiply_vector",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_matrix4x4f_multiply_vector(
              f,
              arguments,
              version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_sampler2d_texture",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_sampler2d_texture(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_sampler2d_texture_projective_3f",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_sampler2d_texture_projective_3f(
              f,
              arguments,
              version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_sampler2d_texture_projective_4f",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_sampler2d_texture_projective_4f(
              f,
              arguments,
              version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_sampler_cube_texture",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_sampler_cube_texture(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2f_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2f_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2i_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2i_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_cross",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_cross(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3f_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3f_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3i_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3i_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4f_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4f_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)

        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_subtract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_add",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_add(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_add_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_add_scalar(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_dot",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_dot(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_interpolate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4i_interpolate(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_magnitude",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_magnitude(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_multiply",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_multiply(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_multiply_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4i_multiply_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_negate",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_negate(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_normalize",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_normalize(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_reflect",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_reflect(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_refract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_refract(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_subtract",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_subtract(
            f,
            arguments,
            version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4i_subtract_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4f_subtract_scalar(f, arguments, version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3i_subtract_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3f_subtract_scalar(f, arguments, version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2i_subtract_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_subtract_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2f_subtract_scalar(f, arguments, version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2f_divide(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector2i_divide(
            f,
            arguments,
            version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3f_divide(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector3i_divide(
            f,
            arguments,
            version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4f_divide(
            f,
            arguments,
            version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_divide",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters.com_io7m_parasol_vector4i_divide(
            f,
            arguments,
            version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2f_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2f_divide_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector2i_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector2i_divide_scalar(f, arguments, version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3f_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3f_divide_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector3i_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector3i_divide_scalar(f, arguments, version);
        }
      });

    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4f_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4f_divide_scalar(f, arguments, version);
        }
      });
    GFFI.EXPRESSION_EMITTERS.put(
      "com_io7m_parasol_vector4i_divide_scalar",
      new GFFIExpressionEmitterType() {
        @Override public GFFIExpression emitExpression(
          final TASTDFunctionExternal f,
          final List<GASTExpressionType> arguments,
          final GVersionType version)
        {
          return GFFIExpressionEmitters
            .com_io7m_parasol_vector4i_divide_scalar(f, arguments, version);
        }
      });
  }

  // CHECKSTYLE:ON

  /**
   * Construct a new FFI.
   * 
   * @param log
   *          The log
   * @return A new FFI
   */

  public static GFFI newFFI(
    final LogUsableType log)
  {
    return new GFFI(log);
  }

  private final LogUsableType log;

  private GFFI(
    final LogUsableType in_log)
  {
    this.log = NullCheck.notNull(in_log, "Log").with("ffi");
  }

  /**
   * Get an FFI expression for the given function application.
   * 
   * @param f
   *          The function
   * @param arguments
   *          The arguments
   * @param version
   *          The GLSL version
   * @return An expression
   * @throws GFFIError
   *           If an FFI error occurs
   */

  public GFFIExpression getExpression(
    final TASTDFunctionExternal f,
    final List<GASTExpressionType> arguments,
    final GVersionType version)
    throws GFFIError
  {
    final TASTDExternal ext = f.getExternal();
    final TokenIdentifierLower ename = ext.getName();
    final String name = ename.getActual();

    if (this.log.wouldLog(LogLevel.LOG_DEBUG)) {
      this.log.debug(String.format(
        "expression for %s at %s:%s",
        name,
        ename.getFile(),
        ename.getPosition()));
    }

    if (GFFI.EXPRESSION_EMITTERS.containsKey(name)) {
      final GFFIExpressionEmitterType e = GFFI.EXPRESSION_EMITTERS.get(name);
      return e.emitExpression(f, arguments, version);
    }
    throw GFFIError.unknownExternal(ext);
  }

  /**
   * Get a function declaration for the given function, if one is required.
   * 
   * @param f
   *          The function
   * @param version
   *          The GLSL version
   * @return A function declaration
   */

  public @Nullable TASTDFunctionDefined getFunctionDefinition(
    final TASTDFunctionExternal f,
    final GVersionType version)
  {
    final TASTDExternal ext = f.getExternal();
    final TokenIdentifierLower ename = ext.getName();
    final String name = ename.getActual();

    if (this.log.wouldLog(LogLevel.LOG_DEBUG)) {
      this.log.debug(String.format(
        "definition for %s at %s:%s",
        name,
        ename.getFile(),
        ename.getPosition()));
    }

    final FunctionType<GVersionType, Boolean> require_check =
      GFFI.DECLARATION_FUNCTION_REQUIRED.get(name);
    if (require_check != null) {
      final boolean required = require_check.call(version).booleanValue();
      if (required) {
        if (this.log.wouldLog(LogLevel.LOG_DEBUG)) {
          this.log.debug(String.format(
            "fallback required for %s at %s:%s",
            name,
            ename.getFile(),
            ename.getPosition()));
        }

        assert ext.getEmulation().isSome();
        final Some<TASTExpressionType> emu =
          (Some<TASTExpressionType>) ext.getEmulation();
        return new TASTDFunctionDefined(
          f.getName(),
          f.getArguments(),
          emu.get(),
          f.getType());
      }
    }

    if (this.log.wouldLog(LogLevel.LOG_DEBUG)) {
      this.log.debug(String.format(
        "no fallback required for %s at %s:%s",
        name,
        ename.getFile(),
        ename.getPosition()));
    }

    return null;
  }

  /**
   * Get a value declaration for the given value, if one is required.
   * 
   * @param v
   *          The value
   * @param version
   *          The GLSL version
   * @return A value declaration
   * @throws GFFIError
   *           If an FFI error occurs
   */

  public @Nullable TASTDValueDefined getValueDefinition(
    final TASTDValueExternal v,
    final GVersionType version)
    throws GFFIError
  {
    final TASTDExternal ext = v.getExternal();
    final TokenIdentifierLower ename = ext.getName();
    final String name = ename.getActual();

    if (this.log.wouldLog(LogLevel.LOG_DEBUG)) {
      this.log.debug(String.format(
        "definition for %s at %s:%s",
        name,
        ename.getFile(),
        ename.getPosition()));
    }

    if (GFFI.DECLARATION_VALUE_EXPRESSIONS.containsKey(name) == false) {
      throw GFFIError.unknownExternal(ext);
    }

    final FunctionType<TASTDValueExternal, TASTExpressionType> emitter =
      GFFI.DECLARATION_VALUE_EXPRESSIONS.get(name);

    final TASTExpressionType exp = emitter.call(v);
    assert exp.getType().equals(v.getType());
    return new TASTDValueDefined(v.getName(), exp);
  }
}
